[package]
name = "tengo-lsp"
version = "0.2.4"
edition = "2021"

[dependencies]
tower-lsp = "0.20"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std"] }
tree-sitter = "0.25"
tree-sitter-language = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dashmap = "6"
log = "0.4"
env_logger = "0.11"

[dependencies.tree-sitter-tengo]
git = "https://github.com/popoffvg/tree-sitter-tengo"
rev = "0184f5bc04e3e9999ae1394612d2ee6495102fec"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
