#!/usr/bin/env bash
# Generate the Homebrew formula for tengo-lsp by downloading the release
# tarballs for a given version and computing their sha256 sums.
#
# Usage: scripts/gen-homebrew-formula.sh <version> > Formula/tengo-lsp.rb
#   <version>  release version without leading "v" (e.g. 0.2.4)
#
# Requires: gh (authenticated), shasum.
set -euo pipefail

VERSION="${1:?usage: gen-homebrew-formula.sh <version>}"
VERSION="${VERSION#v}"
REPO="popoffvg/tengo-lsp"
TAG="v${VERSION}"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

gh release download "$TAG" --repo "$REPO" --pattern '*.tar.gz' --dir "$workdir"

sha() { shasum -a 256 "$workdir/$1" | awk '{print $1}'; }

DARWIN_ARM64="$(sha tengo-lsp-darwin-aarch64.tar.gz)"
DARWIN_X86="$(sha tengo-lsp-darwin-x86_64.tar.gz)"
LINUX_ARM64="$(sha tengo-lsp-linux-aarch64.tar.gz)"
LINUX_X86="$(sha tengo-lsp-linux-x86_64.tar.gz)"

base="https://github.com/${REPO}/releases/download/v#{version}"

cat <<EOF
# This file is generated by scripts/gen-homebrew-formula.sh in popoffvg/tengo-lsp.
# Do not edit by hand; it is overwritten on every release.
class TengoLsp < Formula
  desc "Language server for the Tengo scripting language"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"

  on_macos do
    on_arm do
      url "${base}/tengo-lsp-darwin-aarch64.tar.gz"
      sha256 "${DARWIN_ARM64}"
    end
    on_intel do
      url "${base}/tengo-lsp-darwin-x86_64.tar.gz"
      sha256 "${DARWIN_X86}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/tengo-lsp-linux-aarch64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "${base}/tengo-lsp-linux-x86_64.tar.gz"
      sha256 "${LINUX_X86}"
    end
  end

  def install
    bin.install "tengo-lsp"
  end

  test do
    assert_equal "x := 1\n", pipe_output("#{bin}/tengo-lsp fmt", "x := 1\n")
  end
end
EOF
